### ISSUE TITLE
Remove unneeded version_compares

### ISSUE THREAD

**Issue by fonsecas72** [Halleck45/PhpMetrics#101]
Because hoa/core ~2.0 requires PHP >=5.4.0, Php-Metrics ended up requiring that PHP version as well so it seems to me that we have some unneeded ```version_compare(PHP_VERSION, '5.4.0') >= 0```

Perhaps we should remove those.

**Comment by UFOMelkor** [comment]
:+1:

If we do so, we should IMHO add `php >= 5.4` to our dependencies. `hoa/core` might change to `php >= 5.33` without a bc break, so it's up to us to ensure that phpmetrics runs once it's installed.

There is also a `version_compare('5.0.4', PHP_VERSION)`, this might be removed also.

**Comment by fonsecas72** [comment]
So it seems to me that this leaves us with two options:
* Php-Metrics should support PHP >= 5.3 and we should lower hoa/core dependency.
* Php-Metrics should support PHP >= 5.4 and we should remove every line of code that is <= PHP 5.4 related.
(this does not affect the target version its just the PHP dependency for Php-Metrics it self to run)
@Halleck45 which option will we choose? 
I vote to leave PHP 5.3 support. The less code the better.
What do you think @UFOMelkor?

**Comment by TomasVotruba** [comment]
This might help to decide http://php.net/supported-versions.php

**Comment by Halleck45** [comment]
Hum... I think also that we should leave PHP 5.3 support. 

Who want make a litte PR to change minimum version in `composer.json`? :)

**Comment by TomasVotruba** [comment]
@Halleck45 Like this #144?

**Comment by Halleck45** [comment]
PHP 5.4 is now required

All `version_compare` are preserved: even if we need to have PHP 5.4 to **install** phpmetrics, today **phar archive** continues to work with PHP 5.3
