### ISSUE TITLE
Support traits

### ISSUE THREAD

**Issue by UFOMelkor** [Halleck45/PhpMetrics#115]
Actual traits are unsupported. I'd like to implement this, but we should clarify before whether we drop support for php 5.3 or not (see #101).

**Comment by fonsecas72** [comment]
I don't think PhpMetrics will drop support for PHP 5.4 as a target PHP version besides that issue is about dropping the support for PHP 5.3 anyway.
I would like to have traits supported in PhpMetrics :)

**Comment by UFOMelkor** [comment]
My fault, i meant PHP 5.3 -.-

**Comment by Halleck45** [comment]
Hi, does this issue still available ?

**Comment by UFOMelkor** [comment]
No, has been resolved :+1:

**Comment by niconoe-** [comment]
This should be reopened as PHPMetrics v2.2.0 is ignoring trait once again :cry:.
I have a full trait library that is not parsed as expected because of this.
