### ISSUE TITLE
Failure condition not working

### ISSUE THREAD

**Issue by mrjulio** [Halleck45/PhpMetrics#127]
```bash
#!/usr/bin/env bash

OUTPUT=$(./phpmetrics.phar --failure-condition="sum.loc > 0" test.php)

echo $?
```

Returns 0 instead of **1** with `test.php` having 100+ lines of code.

**Comment by Halleck45** [comment]
Hi,

thanks for the report. Can you confirm that [this commit](https://github.com/Halleck45/PhpMetrics/commit/d19b81b224e5ca78ed75e63b4223d158f75264da) has fixed your issue ?

**Comment by mrjulio** [comment]
Hi,

It's working! Thanks!!

PS: awesome tool btw

**Comment by Halleck45** [comment]
Thanks @mrjulio  :)
