### ISSUE TITLE
It seems that phpmetrics returns invalid exit code 

### ISSUE THREAD

**Issue by mekras** [Halleck45/PhpMetrics#132]
After fixing #127 phpmetrics now returns 1 exit code on success and 0 on fail:
```
$ phpmetrics src; echo $?
PHPMetrics by Jean-François Lépine <https://twitter.com/Halleck45>
                                                                               
Maintainability.................... 85.19 / 100
Accessibility for new developers... 88.81 / 100
Simplicity of algorithms........... 63.14 / 100
Volume............................. 57.75 / 100
Reducing bug's probability......... 68.85 / 100

done
1
```
It seems that [here](https://github.com/Halleck45/PhpMetrics/blob/d19b81b224e5ca78ed75e63b4223d158f75264da/src/Hal/Application/Command/RunMetricsCommand.php#L128) instead of
```php
return $result->isValid() ? 1 : 0;
```
should be
```php
return $result->isValid() ? 0 : 1;
```

**Comment by Halleck45** [comment]
Hello,

`$result` is "condition of failure", not "condition of success". It's very ambiguous :/

    isValid() == true -> condition of failure is satisfied => program fails => return 1;
    isValid() == false -> condition of failure is not satisfied => program doesn't fail => return 0;

So that's not a bug

**Comment by mekras** [comment]
Well, in this case, it would be useful to display a message about failed condition. Current output is misleading, that all is good.

**Comment by Halleck45** [comment]
I hop that [this commit](https://github.com/Halleck45/PhpMetrics/commit/5c5634727fbdd8e0c833417e99756871d2256a2d) fixes the problem. Can you confirm please ?

**Comment by edrush** [comment]
Fixes for me the problem that Jenkins marked builds as failure while everything was fine. Thank you!

**Comment by mremi** [comment]
:+1: but a little bit confusing

**Comment by Halleck45** [comment]
@mekras is it also ok for you ?

**Comment by mekras** [comment]
Yes. Now all works fine. Thanks.

**Comment by Halleck45** [comment]
Cool :) . I close this issue
