### ISSUE TITLE
Can we analyze specific files? e.g. a pull request's files

### ISSUE THREAD

**Issue by HoffmannAndras** [Halleck45/PhpMetrics#135]

**Comment by Halleck45** [comment]
Hi,

No, you should specify one directory or one file. If you want, you can group specific files into temporary folder, then run analysis on this folder.

About Pull Request, I think that's possible, with code like this (not tested):
```
mkdir -p /tmp/destination
for file in $(git diff --name-only); do
  cp file /tmp/destination
done

phpmetrics /tmp/destination
```

**Comment by HoffmannAndras** [comment]
Its enough, Thanks.
