### ISSUE TITLE
Iframe height when publishing phpmetrics report on Jenkins (HTML Publish Plugin)

### ISSUE THREAD

**Issue by tophsic** [Halleck45/PhpMetrics#141]
When I publish PhpMetrics HTML report on Jenkins via HTML Publish Plugin. I observe a very annoying bug on Iframe height wich present the report.

Jenkins 1.601
HTML Publish Plugin 1.3

Jenkins configuration

![jenkins_configuration](https://cloud.githubusercontent.com/assets/930980/8984518/5617b182-36d2-11e5-90f4-e2a975bd0b3c.png)

HTML code of Iframe on HTML report
```html
<iframe id="myframe" height="100%" width="100%" frameborder="0" src="phpmetrics.html" style="height: 300px;"></iframe>
```

![html_report](https://cloud.githubusercontent.com/assets/930980/8984761/0292ef5c-36d4-11e5-9be6-a3032eb5a619.png)

I can not see directly all the report.

The `style="height:300px;"` is set by https://github.com/Halleck45/PhpMetrics/blob/master/templates/html/summary/report-maintainability.js.twig#L147 and `maxWidth` by https://github.com/Halleck45/PhpMetrics/blob/master/templates/html/summary/report-maintainability.js.twig#L10

Any idea if I can do something with my Jenkins configuration or this is a PhpMetrics problem ?

**Comment by Halleck45** [comment]
Yes, I've the same issue with Jenkins. I don't think that we can resolve this problem in PhpMetric' code. To fix it I set the height of my iframe to 800 and more.

    <iframe id="myframe" height="100%" width="100%" frameborder="0" src="phpmetrics.html" style="height: 800;"></iframe>

**Comment by tophsic** [comment]
It doesn't work with inline code but in a CSS rule for me.

I search where the code of `htmlpublisher-wrapper.html` file in [HTML Publisher Plugin](https://wiki.jenkins-ci.org/display/JENKINS/HTML+Publisher+Plugin) but didn't find it :unamused: to avoid manual edition all the time.

**Comment by jacek-berlin** [comment]
I have same problem, 
where can I fix it?

**Comment by lukeduda** [comment]
Same here, any idea?

**Comment by lukeduda** [comment]
My fix - delete js line which generates iframe resizing:
`sed -i 's/d3.select(self.frameElement).style("height", maxWidth + "px");//g' ./phpmetrics.html`

I'm executing this command after phpmetrics html report comand is done.
