### ISSUE TITLE
Maintainability Index + colours

### ISSUE THREAD

**Issue by TomBZombie** [Halleck45/PhpMetrics#142]
I'm not sure what the thresholds are for each colour but it's seemingly impossible to get a 'green' class. The following code:

```php
<?php
namespace Test;
class Test {
	private $foo;

	public function __construct(Foo $foo) {
		$this->foo = $foo;
	}
}
```

Shows as orange with a Maintainability Index of 77. If a class with 1 method and 1 variable shows as orange, surely the threshold for colours is far too high? Presumably the only thing that shows as green is an interface with one method?

edit: I'm not sure what's wrong, possibly a setting? 

The example here: http://www.phpmetrics.org/report/latest/index.html

shows this class: 
https://github.com/Halleck45/PhpMetrics/blob/master/src/Hal/Component/Evaluation/Evaluator.php

As green with a "Maintainability Index" of 87... can you explain how this is calculated? The example class above is a lot less complex by any measure.

**Comment by rexem** [comment]
Maintainability index takes comments into account (since it's the metric of how easy it is to maintain the code, rather than how short/simple it is), thus just add:
```
/**
* Description of the class
*/
```
on top of your ```class Test {``` and I'm sure you'll get your maintainability well in the green range

**Comment by TomBZombie** [comment]
aha that makes sense.

**Comment by rexem** [comment]
Maintainability is calculated by adding "maintainability without comments" (MIwC) and "Comments Weight" (CommW) fields. Thus, for the example you linked to we get:
``` MIwC + CommW = 39.42 + 48.29 = 87.71 ```

CommW is ```50 * sin( sqrt( 2.4 * 33 / 96 ) )``` [where 33 is comments LOC, 96 - LOC]

MIwC is ```(171 - (5.2 * ln(Volume)) - (0.23 * Complexity) - (16.2 * ln(LLOC))) * 100 / 171 = (171 - (5.2 * ln(1020.09)) - (0.23 * 7) - (16.2 * ln(23))) * 100 / 171 = 48.29```

I hope that helps

**Comment by Halleck45** [comment]
@TomBZombie nothing is arbitrary, PhpMetrics just apply "official" formulas.

@rexem you're write. Note that Maintainability index takes care about volume : a big code (lot of lines of code) can be more complex than short code and have better Maintainability index.

Can I close this issue ?
