### ISSUE TITLE
Bug in html-layout on site phpmetrics.org

### ISSUE THREAD

**Issue by samizdam** [Halleck45/PhpMetrics#146]
On all pages layout is broken (hide under left menu-bar), in Firefox 40-41, Win7: 
![fireshot screen capture 006 - metrics of phpmetrics - www_phpmetrics_org__documentation_index_html](https://cloud.githubusercontent.com/assets/1556299/9546288/346f9bf6-4d9a-11e5-9fb2-bdfcad70ef1d.png)
![fireshot screen capture 007 - phpmetrics - www_phpmetrics_org](https://cloud.githubusercontent.com/assets/1556299/9546360/b3b42ac6-4d9a-11e5-860b-f9df8effa876.png)

**Comment by rexem** [comment]
Just to add, it affects all browsers when the screen size less than ~1650px

@Halleck45 seems like a typo in the HTML at line 99:
```mui-cold-md-10``` should be ```mui-col-md-10```

**Comment by Halleck45** [comment]
@rexem Cool, thanks a lot ! I'll fix it this week-end
