### ISSUE TITLE
Fix return code for successful command execution

### ISSUE THREAD

**Issue by Chintanvpatel** [Halleck45/PhpMetrics#147]
Hello,
When phpmetrics generate html successfully, it should return 0 as exit code.

Thanks,
Chintan V. Patel

**Comment by cbastienbaron** [comment]
:+1:  that is a pbl for automatic report . there is a workaround ?

**Comment by Halleck45** [comment]
Does [this commit](https://github.com/Halleck45/PhpMetrics/commit/5c5634727fbdd8e0c833417e99756871d2256a2d) fixes the problem ?

**Comment by Chintanvpatel** [comment]
@Halleck45 this issue is fixed.
