### ISSUE TITLE
Class and Interface Name contains line breaks

### ISSUE THREAD

**Issue by devosc** [Halleck45/PhpMetrics#150]
It seems like some classes that have line breaks before the keywords extends or implements end up with the class/interface name and then the line break and the extends/implements keyword, e.g

```
Route
    extends
```

Adding the following to both `InterfaceExtractor` and `ClassExtractor` seems to resolve this.

```
if (false !== $pos = strpos($classname, "\n")) {
    $classname = substr($classname, 0, $pos);
}
```

Otherwise there is a difference in the Afferent coupling, e.g 0.09 instead of 0.12.

The strpos workaround is probably not ideal, but I'm not sure about the `getFollowingName` function. If you prefer a PR for the strpos, let me know. Thanks.

**Comment by Halleck45** [comment]
Hi,

can you confirm that the bug is fixed for you ?

Thanks for your help :)
