### ISSUE TITLE
Exit code and TeamCity

### ISSUE THREAD

**Issue by SmetDenis** [Halleck45/PhpMetrics#151]
Hi

First of all thanks for the tool!

Today I updated my CI server (with teamcity) and everything was awesome but phpmetrics became fail with incorrect exit code. I don't now why...

I use command line to call
```
mkdir -p build/phpmetrics

phpmetrics ./src \
    --report-html=build/phpmetrics/report.html \
    --report-xml=build/phpmetrics/report.xml \
    --report-csv=build/phpmetrics/report.csv \
    --report-json=build/phpmetrics/report.json \
    --violations-xml=build/phpmetrics/violations.xml \
    --verbose \
    --no-ansi \
    --no-interaction
```
LIb for testing is https://github.com/JBZoo/SimpleTypes

And my problem in exit code. Teamcity thinks that build step is failed.
![image](https://cloud.githubusercontent.com/assets/1118678/10335412/4155b098-6d12-11e5-97c1-ff6f26ce5db7.png)

So, i think that problem in RunMetricsCommand.php
```
return $result->isValid() ? 1 : 0;
```

If I replace 1 and 0 the build step finish successfully.

Correct exit code is very important stuff and "1" ussually is some error and  "0" - everything is awesome. php.net thinks the same.

![image](https://cloud.githubusercontent.com/assets/1118678/10335505/034dd6f8-6d13-11e5-9c8c-af2459b210cd.png)

if it's really error code well why key "verbose" didn't show me any messages?

Thanks and best regards.
SmetDenis.

**Comment by Chintanvpatel** [comment]
Hello SmetDenis,
Yes. This is related to #147

**Comment by SmetDenis** [comment]
Well....
I see it's really old bug https://github.com/Halleck45/PhpMetrics/issues/132
Too bad

**Comment by Halleck45** [comment]
Hi,

My fault, I I had not considered the case where no condition is provided.

I've added some function tests. Can you confirm that's is OK for you ?

**Comment by SmetDenis** [comment]
Yeah! Thanks. Everything is awesome.
