### ISSUE TITLE
Accessibility for new developers

### ISSUE THREAD

**Issue by xtrasmal** [Halleck45/PhpMetrics#152]
Hi there,

I got I question about refactoring my codebase to improve the score on the "Accessibility for new developers". What does it measure and how can I make sure that on greenfield projects, this stays on 100 percent?

**Comment by xtrasmal** [comment]
Ah wait :p found it in the source. So it's just a matter of commenting and keeping the lines of code to a minimum right? It doesn't take in account the abstractness of code.

**Comment by Halleck45** [comment]
No, this is a really very basic indicator...
