### ISSUE TITLE
PHP 7 features support

### ISSUE THREAD

**Issue by ypppa** [Halleck45/PhpMetrics#171]
1. The null coalescing operator (??) has been added as syntactic sugar for the common case of needing to use a ternary in conjunction with isset(). It returns its first operand if it exists and is not NULL; otherwise it returns its second operand.

2. Classes, functions and constants being imported from the same namespace can now be grouped together in a single use statement.

Now analyzer returns: "file fooBar.php is not valid and has been skipped"

**Comment by Halleck45** [comment]
Hi,

If you use analyze PHP7 code with PHP5 interpreter, you should use the [--ignore-errors](https://github.com/Halleck45/PhpMetrics#compatibility) option
