### ISSUE TITLE
Parse error in /vendor/hoa/core/Core.php

### ISSUE THREAD

**Issue by Maknash** [Halleck45/PhpMetrics#178]
Hello,

I've just installed phpmetrics and when I try to test it, I get this error :

C:\wamp_22\bin\php\php5.3.10>php phpmetrics.phar --report-html=report.html F:\workspace_php\myproject

Parse error: syntax error, unexpected '[' in phar://C:/wamp_22/bin/php/php5.3.10/phpmetrics.phar/vendor/hoa/core/Core.php on line 99

Call Stack:
    0.0147     936232   1. {main}() C:\wamp_22\bin\php\php5.3.10\phpmetrics.phar:0
    0.0148     930096   2. require_once('phar://C:/wamp_22/bin/php/php5.3.10/phpmetrics.phar/vendor/autoload.php') C:\wamp_22\bin\php\php5.3.10\phpmetrics.phar:15
    0.0156     953160   3. ComposerAutoloaderInit76102e2da601cbb6bcbedd8bb8cc5634::getLoader() phar://C:/wamp_22/bin/php/php5.3.10/phpmetrics.phar/vendor/autoload.php:7
    0.0201    1328264   4. composerRequire76102e2da601cbb6bcbedd8bb8cc5634() phar://C:/wamp_22/bin/php/php5.3.10/phpmetrics.phar/vendor/composer/autoload_real.php:45

**Comment by Maknash** [comment]
The corresponding line is $app = new Hal\Application\Console\PhpMetricsApplication('PhpMetrics, by Jean-François Lépine (https://twitter.com/Halleck45)', 'v1.8.3'); // version will be inserted by build.

**Comment by UFOMelkor** [comment]
PhpMetrics needs at least php 5.4 (see #101).
Are you using php 5.3?

**Comment by Everyways** [comment]
yep (5.6)

2016-02-04 19:28 GMT+01:00 Oskar Bley <notifications@github.com>:

**Comment by Maknash** [comment]
Thanks for your answer.
Yes, I use php5.3.10, but I just realize my variable environment "Path" was set on php5.2.7... but phpmetrics.phar still not working. So I've installed PHPMetrics by Composer with this composer.json :
`{
    "require": {
        "halleck45/phpmetrics" : "@stable"
    }
}`
Now, it works with metrics.php.bat ! :)
