### ISSUE TITLE
parent treated as a class

### ISSUE THREAD

**Issue by Trismegiste** [Halleck45/PhpMetrics#50]
"parent" is shown as a class in the relations graph : (tested on [Mondrian](https://github.com/Trismegiste/Mondrian) )

![image](https://cloud.githubusercontent.com/assets/1260026/4238397/0473c6b0-39d8-11e4-8be2-63894ed5baf9.png)

It's not a big deal but it's a little confusing. And I think perhaps it might affect some other metrics if PhpMetrics is seeing this call as a static call ?

Hope this helps :beer:

**Comment by hugofonseca** [comment]
I think #89 fixes this.
