### ISSUE TITLE
Call to a member function getConcreteClasses() on a non-object

### ISSUE THREAD

**Issue by ThePixelDeveloper** [Halleck45/PhpMetrics#73]
Following on from #72 I decided to play around with the options and had more success with the ``--without-oop` flag although still ran into issues.

```
➜  web git:(master) phpmetrics . --report-html ../html --without-oop
PHPMetrics by Jean-François Lépine <https://twitter.com/Halleck45>

  139/1295 [===>------------------------]  10%
  149/1295 [===>------------------------]  11%
  151/1295 [===>------------------------]  11%
  215/1295 [====>-----------------------]  16%
  216/1295 [====>-----------------------]  16%
  224/1295 [====>-----------------------]  17%
  879/1295 [===================>--------]  67%
                                              
Grouping results by package/directory. This will take few minutes...           

PHP Fatal error:  Call to a member function getConcreteClasses() on a non-object in phar:///usr/local/bin/phpmetrics/src/Hal/Metrics/Mood/Abstractness/Abstractness.php on line 33

**Comment by Halleck45** [comment]
You right. I think that I'll remove this "historical" option.

**Comment by baptistedeleplace** [comment]
The error trace:


PHP Fatal error:  Call to a member function getConcreteClasses() on a non-object in /phpmetrics/src/Hal/Metrics/Mood/Abstractness/Abstractness.php on line 33
PHP Stack trace:
PHP   1. {main}() /phpmetrics/bin/phpmetrics:0
PHP   2. Symfony\Component\Console\Application->run() /phpmetrics/bin/phpmetrics:22
PHP   3. Symfony\Component\Console\Application->doRun() /phpmetrics/vendor/symfony/console/Symfony/Component/Console/Application.php:126
PHP   4. Symfony\Component\Console\Application->doRunCommand() /phpmetrics/vendor/symfony/console/Symfony/Component/Console/Application.php:195
PHP   5. Symfony\Component\Console\Command\Command->run() /phpmetrics/vendor/symfony/console/Symfony/Component/Console/Application.php:874
PHP   6. Hal\Application\Command\RunMetricsCommand->execute() /phpmetrics/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
PHP   7. Hal\Application\Command\Job\Queue->execute() /phpmetrics/src/Hal/Application/Command/RunMetricsCommand.php:119
PHP   8. Hal\Application\Command\Job\DoAggregatedAnalyze->execute() /phpmetrics/src/Hal/Application/Command/Job/Queue.php:51
PHP   9. Hal\Metrics\Mood\Abstractness\Abstractness->calculate() /phpmetrics/src/Hal/Application/Command/Job/DoAggregatedAnalyze.php:80
