### ISSUE TITLE
Does it look for a default config?

### ISSUE THREAD

**Issue by sagikazarmark** [Halleck45/PhpMetrics#74]
For example phpmetrics.yml[.dist]? It would be awesome to be able to run `phpmetrics` and enjoy.

**Comment by hugofonseca** [comment]
So https://github.com/Halleck45/PhpMetrics#configuration-file does not fulfill your purpose?

**Comment by sagikazarmark** [comment]
Well, I am saying that it would be awesome if I didn't have to define where to look for the config file every time.

`phpmetrics` done.

**Comment by hugofonseca** [comment]
oh, some .phpmetrics like [.php_cs](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.5/.php_cs) used in [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer). That seems nice :)

**Comment by sagikazarmark** [comment]
Exactly. Either with dot or without it. IMO the common setup is the following:

* In the project dir look for phpmetrics.yml[.dist]
* In the home dir look for .phpmetrics.yml (and merge into per project setup if any)

**Comment by hugofonseca** [comment]
ok, so, what's missing from default configuration? 
I mean, what would you put in the phpmetrics.yml?

**Comment by hugofonseca** [comment]
Forget my last comment :P I got this wrong.

**Comment by hugofonseca** [comment]
@sagikazarmark can you please try my fix? It should look for the file at the directory where the phpmetrics command gets called.

**Comment by sagikazarmark** [comment]
Sure, will look at it at the weekend

**Comment by Halleck45** [comment]
#90 is merge, I close this issue
