### ISSUE TITLE
Is something wrong with chart-bubbles 

### ISSUE THREAD

**Issue by hugofonseca** [Halleck45/PhpMetrics#75]
I try with PhpMetrics project itself:
```
bin/phpmetrics --chart-bubbles=chart.svg .
```
And I got this:
![chart](https://cloud.githubusercontent.com/assets/1098293/5743062/9bd2638e-9c0e-11e4-9ec4-8b634c2f631a.png)

**Comment by Halleck45** [comment]
That's the "poor" bubble chart. If you want the beautiful report (with all charts), prefer the `--report-html` option

**Comment by hugofonseca** [comment]
I looking to export this .svg img. so I can use it somewhere else, e.g. send it by email.
Is there anyway to achieve this?

**Comment by Halleck45** [comment]
There are two ways:

+ Manually open the HTML report, then click on "save as SVG" link in front of each image.
+ Automatically save the SVG, using, for example, [this script](https://gist.github.com/devosc/6f52d03e0821faf389b5#)

**Comment by hugofonseca** [comment]
Ok, thanks! :) 
Manually is not an option and scripting is not something I would like to do but I'll look into this further and try something.

**Comment by Halleck45** [comment]
Ok. Good luck ! Do not hesitate to contribute :)
