### ISSUE TITLE
no global php version available

### ISSUE THREAD

**Issue by mi-schi** [Halleck45/PhpMetrics#83]
The SyntaxChecker in Hal\Component\File went wrong, because the method isCorrect can't find a global php version. On our servers there is no global php version available. Also a symlink is a bad idea, because of maintainability reasons.
The error message is "file %s is not valid and has been skipped" in line 114 in the DoAnalyze class in the namespace Hal\Application\Command\Job.

**Comment by tommy-muehle** [comment]
+1
An option would be the use of [PHP_BINARY](http://php.net/manual/en/reserved.constants.php) constant. So you can get the binary that startet the phar file. Available since PHP 5.4.

**Comment by fonsecas72** [comment]
@tommy-muehle @mi-schi @Halleck45 I think we can close this.

**Comment by Halleck45** [comment]
I close this issue. Thanks !
